FROM mdillon/postgis

RUN apt-get update &&\
    apt-get install -y gdal-bin libgdal-dev wget unzip &&\
    export CPLUS_INCLUDE_PATH=/usr/include/gdal &&\
    export C_INCLUDE_PATH=/usr/include/gdal




