name: Deploy Default Image

on:
  push:
    paths:
      - './jupyterhub/workspaces/**'

  workflow_dispatch:

jobs:

  deploy-default-image:

    runs-on: ubuntu-latest 
    
    steps:

    - uses: actions/checkout@v2
     
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.AWS_ACCESS_KEY_ID }}"  
        password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        registry: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com"
        image_name: ./jupyterhub/workspaces/geospatial
        image_tag: development
        push_image_and_stages: true