name: Apply Terraform

on:
  push:
    paths:
      - '**.tf'
      - '**.rb'

  workflow_dispatch:

jobs:

  terraform-apply-chef-infra:

    runs-on: ubuntu-latest 
    env:
      tf_version: '1.0.3'
      tf_working_dir: ./terraform/chef/
      tf_modules_dir: ./terraform/modules/**
      chef_username: dmw2151

    steps:
      
      - uses: actions/checkout@v2

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          args: '-var="deployer_ip=${{ secrets.CHEF_SSH_VPC_CIDR }}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     
      - name: Terraform Format - Main
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
        
      - name: Terraform Format - Modules
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ env.tf_modules_dir }}

      - name: Terraform Validate - All
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply - All
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          args: '-var="deployer_ip=${{ secrets.CHEF_SSH_VPC_CIDR }}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      - name: Terraform Get Output
        id: terraform
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'output'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Setting environment variables..
        run: |
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
      
      - name: Install Apt
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq 

      - name: Add Github Actions IP to Security group
        run: |
          set -x;
          AWS__SG=`( echo ${{ steps.terraform.outputs.tf_actions_output }} | jq -r '.ssh_group_id.value' )`
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS__SG \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32    
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}

      - name: Copy Cookbook to WorkStation
        uses: appleboy/scp-action@master
        with:
          host: $(echo  ${{ steps.terraform.outputs.tf_actions_output.workstation_ip  }} | jq -r '.ssh_group_id.value' )
          username: "ubuntu"
          port: 22
          key: ${{ secrets.CHEF__WORKSTATION_SSH_KEY }}
          source: "./chef-repo/cookbooks/jupyter/"
          target: "~/chef-repo/cookbooks/"
      
      - name: Update Client Nodes
        uses: appleboy/ssh-action@master
        env:
          CHEF__USER_NAME: ${{ env.chef_username }} 
        with:
          host: $(echo  ${{ steps.terraform.outputs.tf_actions_output.workstation_ip  }} | jq -r '.ssh_group_id.value' )
          username: "ubuntu"
          key: ${{ secrets.CHEF__WORKSTATION_SSH_KEY }}
          port: 22
          envs: CHEF__USER_NAME
          script: |
            ./scripts/workstation_to_infra_push.sh

      - name: Remove Github Actions IP from Security Group
        run: |
          set -x;
          AWS__SG=`( echo ${{ steps.terraform.outputs.tf_actions_output }} | jq -r '.ssh_group_id.value' )`
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS__SG \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        if: always()